#!/usr/bin/env bash
#
# Keep the operator's flattened CRD and Role under deploy/k3s/manifests/ in step
# with the Go source controller-gen generates them from (docs/PLAN.md D31), and
# the operator chart's crds/ copy of the CRD in step with both (D38).
#
#   hack/manifests.sh write    regenerate, and rewrite each file below its marker
#   hack/manifests.sh verify   regenerate into a scratch directory; exit 1 on any diff
#
# Run it through `make manifests` / `make verify-manifests`, which set
# CONTROLLER_GEN to the pinned binary.
#
# Each flattened file is a hand-written head, the marker line below, and
# controller-gen's output verbatim. Only the part below the marker is generated,
# so only that part is rewritten or compared; the head — comments, and in the
# RBAC file the hand-written ServiceAccount and RoleBinding — is left alone.
# There is no kustomize tree beside these files: this check is what stops the
# types and the manifests from disagreeing silently.
#
# The chart at deploy/helm/mlobs-operator/ carries the CRD under crds/ as a
# byte-exact copy of the whole flattened file, head included, so it is held to
# the same expected bytes: three projections of one Go source, the flattened
# CRD, the flattened Role and the chart's CRD, each checked whole-file. The
# chart's templates are held to the flattened files by hack/helm-parity.sh.
set -euo pipefail

MARKER='# --- generated by controller-gen below this line; do not edit ---'

# controller-gen output -> the flattened file it lives in.
PAIRS=(
  "crd/serving.mlobs.dev_servingdeployments.yaml:01-servingdeployment-crd.yaml"
  "rbac/role.yaml:02-operator-rbac.yaml"
)

die() {
  echo "error: $1" >&2
  exit 1
}

mode="${1:-}"
case "$mode" in
  write | verify) ;;
  *) die "usage: $0 write|verify" ;;
esac
[ -n "${CONTROLLER_GEN:-}" ] || die "CONTROLLER_GEN is not set; run make manifests or make verify-manifests"

OPERATOR_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFESTS_DIR="$(cd -- "${OPERATOR_DIR}/../deploy/k3s/manifests" && pwd)"
CHART_CRDS_DIR="$(cd -- "${OPERATOR_DIR}/../deploy/helm/mlobs-operator/crds" && pwd)"
# The flattened file the chart copies into crds/, under the same name.
CHART_CRD=01-servingdeployment-crd.yaml

work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT
gen_dir="${work_dir}/gen"
expected_dir="${work_dir}/expected"
mkdir -p "$expected_dir"

(cd "$OPERATOR_DIR" && "$CONTROLLER_GEN" rbac:roleName=operator crd paths="./..." \
  output:crd:dir="${gen_dir}/crd" output:rbac:dir="${gen_dir}/rbac")

# A generated file with no flattened home would go unshipped — a second kind's
# CRD, for one. That is a design change, so it stops here rather than passing.
# (A new rule, or a ClusterRole from a marker with no namespace, lands in
# role.yaml and shows up as a diff below.)
while IFS= read -r generated; do
  rel="${generated#"${gen_dir}/"}"
  mapped=false
  for pair in "${PAIRS[@]}"; do
    [ "${pair%%:*}" = "$rel" ] && mapped=true
  done
  "$mapped" || die "controller-gen generated ${rel}, which has no flattened file under deploy/k3s/manifests/"
done < <(find "$gen_dir" -type f | sort)

drift=0

# sync_file TARGET LABEL: in write mode, rewrite TARGET as $expected; in verify
# mode, diff TARGET against it, whole-file.
sync_file() {
  local target="$1" label="$2"
  if [ "$mode" = write ]; then
    cat "$expected" > "$target"
    echo "ok: wrote ${label}"
  elif diff -u "$target" "$expected"; then
    echo "ok: ${label} matches controller-gen"
  else
    echo "error: ${label} differs from controller-gen output; run make -C operator manifests" >&2
    drift=1
  fi
}

for pair in "${PAIRS[@]}"; do
  generated="${gen_dir}/${pair%%:*}"
  name="${pair#*:}"
  target="${MANIFESTS_DIR}/${name}"
  expected="${expected_dir}/${name}"

  [ -f "$generated" ] || die "controller-gen did not generate ${pair%%:*}"
  [ -f "$target" ] || die "missing deploy/k3s/manifests/${name}"
  count="$(grep -cxF -- "$MARKER" "$target" || true)"
  [ "$count" = "1" ] || die "${name} must hold the marker line exactly once (found ${count:-none})"

  awk -v marker="$MARKER" '{ print } $0 == marker { exit }' "$target" > "$expected"
  cat "$generated" >> "$expected"

  # apply.sh sed-substitutes these three tokens in every file under manifests/.
  # One inside a generated field description would be rewritten on every
  # deploy, and nothing downstream would notice. Explicit status, as in CI: a
  # bare `! grep` reads a grep error as "no match".
  status=0
  grep -nE 'IMAGE_PREFIX|IMAGE_TAG|PLACEHOLDER' "$expected" >&2 || status=$?
  case "$status" in
    0) die "${name} would contain a token apply.sh substitutes; reword the Go doc comment or marker it came from" ;;
    1) ;;
    *) die "grep exited with status ${status}" ;;
  esac

  sync_file "$target" "deploy/k3s/manifests/${name}"

  # The chart's copy is the same file, byte for byte, so the same bytes are
  # expected of it.
  if [ "$name" = "$CHART_CRD" ]; then
    chart_copy="${CHART_CRDS_DIR}/${name}"
    [ -f "$chart_copy" ] || [ "$mode" = write ] || die "missing deploy/helm/mlobs-operator/crds/${name}"
    sync_file "$chart_copy" "deploy/helm/mlobs-operator/crds/${name}"
  fi
done

# The chart's crds/ holds that one copy and nothing else: Helm installs every
# file there, and a second one would be a CRD no check projects from the Go
# source.
extra="$(find "$CHART_CRDS_DIR" -mindepth 1 ! -name "$CHART_CRD" | sort)"
[ -z "$extra" ] || die "deploy/helm/mlobs-operator/crds/ holds more than ${CHART_CRD}: ${extra}"
echo "ok: deploy/helm/mlobs-operator/crds/ holds ${CHART_CRD} only"

# The operator's whole grant is one namespaced Role (D33 and its O2 addendum).
# controller-gen emits a ClusterRole for an rbac marker that names no
# namespace, and a hand edit above the marker could add a ClusterRoleBinding
# or point the RoleBinding's roleRef at a ClusterRole; any of them fails here,
# in both modes. Explicit status, as above.
rbac="${MANIFESTS_DIR}/02-operator-rbac.yaml"
status=0
grep -nE 'kind:[[:space:]]*"?ClusterRole' "$rbac" >&2 || status=$?
case "$status" in
  0) die "02-operator-rbac.yaml references a ClusterRole or ClusterRoleBinding; the operator holds one namespaced Role (D33)" ;;
  1) echo "ok: deploy/k3s/manifests/02-operator-rbac.yaml holds no ClusterRole" ;;
  *) die "grep exited with status ${status}" ;;
esac
exit "$drift"
