#!/usr/bin/env bash
#
# Keep the operator's flattened CRD and Role under deploy/k3s/manifests/ in step
# with the Go source controller-gen generates them from (docs/PLAN.md D31).
#
#   hack/manifests.sh write    regenerate, and rewrite each file below its marker
#   hack/manifests.sh verify   regenerate into a scratch directory; exit 1 on any diff
#
# Run it through `make manifests` / `make verify-manifests`, which set
# CONTROLLER_GEN to the pinned binary.
#
# Each flattened file is a hand-written head, the marker line below, and
# controller-gen's output verbatim. Only the part below the marker is generated,
# so only that part is rewritten or compared; the head — comments, and in the
# RBAC file the hand-written ServiceAccount and RoleBinding — is left alone.
# There is no kustomize tree beside these files: this check is what stops the
# types and the manifests from disagreeing silently.
set -euo pipefail

MARKER='# --- generated by controller-gen below this line; do not edit ---'

# controller-gen output -> the flattened file it lives in.
PAIRS=(
  "crd/serving.mlobs.dev_servingdeployments.yaml:01-servingdeployment-crd.yaml"
  "rbac/role.yaml:02-operator-rbac.yaml"
)

die() {
  echo "error: $1" >&2
  exit 1
}

mode="${1:-}"
case "$mode" in
  write | verify) ;;
  *) die "usage: $0 write|verify" ;;
esac
[ -n "${CONTROLLER_GEN:-}" ] || die "CONTROLLER_GEN is not set; run make manifests or make verify-manifests"

OPERATOR_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFESTS_DIR="$(cd -- "${OPERATOR_DIR}/../deploy/k3s/manifests" && pwd)"

work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT
gen_dir="${work_dir}/gen"
expected_dir="${work_dir}/expected"
mkdir -p "$expected_dir"

(cd "$OPERATOR_DIR" && "$CONTROLLER_GEN" rbac:roleName=operator crd paths="./..." \
  output:crd:dir="${gen_dir}/crd" output:rbac:dir="${gen_dir}/rbac")

# A generated file with no flattened home would go unshipped — a second kind's
# CRD, for one. That is a design change, so it stops here rather than passing.
# (A new rule, or a ClusterRole from a marker with no namespace, lands in
# role.yaml and shows up as a diff below.)
while IFS= read -r generated; do
  rel="${generated#"${gen_dir}/"}"
  mapped=false
  for pair in "${PAIRS[@]}"; do
    [ "${pair%%:*}" = "$rel" ] && mapped=true
  done
  "$mapped" || die "controller-gen generated ${rel}, which has no flattened file under deploy/k3s/manifests/"
done < <(find "$gen_dir" -type f | sort)

drift=0
for pair in "${PAIRS[@]}"; do
  generated="${gen_dir}/${pair%%:*}"
  name="${pair#*:}"
  target="${MANIFESTS_DIR}/${name}"
  expected="${expected_dir}/${name}"

  [ -f "$generated" ] || die "controller-gen did not generate ${pair%%:*}"
  [ -f "$target" ] || die "missing deploy/k3s/manifests/${name}"
  count="$(grep -cxF -- "$MARKER" "$target" || true)"
  [ "$count" = "1" ] || die "${name} must hold the marker line exactly once (found ${count:-none})"

  awk -v marker="$MARKER" '{ print } $0 == marker { exit }' "$target" > "$expected"
  cat "$generated" >> "$expected"

  # apply.sh sed-substitutes these three tokens in every file under manifests/.
  # One inside a generated field description would be rewritten on every
  # deploy, and nothing downstream would notice. Explicit status, as in CI: a
  # bare `! grep` reads a grep error as "no match".
  status=0
  grep -nE 'IMAGE_PREFIX|IMAGE_TAG|PLACEHOLDER' "$expected" >&2 || status=$?
  case "$status" in
    0) die "${name} would contain a token apply.sh substitutes; reword the Go doc comment or marker it came from" ;;
    1) ;;
    *) die "grep exited with status ${status}" ;;
  esac

  if [ "$mode" = write ]; then
    cat "$expected" > "$target"
    echo "ok: wrote deploy/k3s/manifests/${name}"
  elif diff -u "$target" "$expected"; then
    echo "ok: deploy/k3s/manifests/${name} matches controller-gen"
  else
    echo "error: deploy/k3s/manifests/${name} differs from controller-gen output; run make -C operator manifests" >&2
    drift=1
  fi
done

# The operator's whole grant is one namespaced Role (D33 and its O2 addendum).
# controller-gen emits a ClusterRole for an rbac marker that names no
# namespace, and a hand edit above the marker could add a ClusterRoleBinding
# or point the RoleBinding's roleRef at a ClusterRole; any of them fails here,
# in both modes. Explicit status, as above.
rbac="${MANIFESTS_DIR}/02-operator-rbac.yaml"
status=0
grep -nE 'kind:[[:space:]]*"?ClusterRole' "$rbac" >&2 || status=$?
case "$status" in
  0) die "02-operator-rbac.yaml references a ClusterRole or ClusterRoleBinding; the operator holds one namespaced Role (D33)" ;;
  1) echo "ok: deploy/k3s/manifests/02-operator-rbac.yaml holds no ClusterRole" ;;
  *) die "grep exited with status ${status}" ;;
esac
exit "$drift"
